# Generated by Django 5.2.9 on 2025-12-06 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('record', models.AutoField(db_column='Record', primary_key=True, serialize=False)),
                ('register_no', models.CharField(db_column='RegisterNo', help_text='Student registration number', max_length=50, validators=[django.core.validators.RegexValidator(message='Register number must be alphanumeric', regex='^[A-Z0-9]+$')])),
                ('student_name', models.CharField(db_column='StudentName', help_text='Full name of the student', max_length=200)),
                ('course_code', models.CharField(db_column='Coursecode', help_text='Course code identifier', max_length=20)),
                ('course_title', models.CharField(db_column='CourseTitle', help_text='Full title of the course', max_length=200)),
                ('exam_date', models.DateField(db_column='ExamDate', help_text='Date of the examination')),
                ('exam_session', models.CharField(db_column='ExamSession', help_text='Session of the exam (e.g., Morning, Afternoon)', max_length=50)),
                ('exam_hall_number', models.CharField(db_column='ExamHallNumber', help_text='Hall number where exam is conducted', max_length=20)),
                ('exam_seat_number', models.CharField(db_column='ExamSeatNumber', help_text='Seat number assigned to the student', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, db_column='DateOfBirth', help_text='Date of birth for authentication', null=True)),
            ],
            options={
                'verbose_name': 'Exam Record',
                'verbose_name_plural': 'Exam Records',
                'db_table': 'ExamRecord',
                'indexes': [models.Index(fields=['register_no'], name='idx_register_no'), models.Index(fields=['exam_date'], name='idx_exam_date')],
            },
        ),
    ]
